Webpack & Photo Preview
htmlacademy-javascript/174891-keksobooking-21 pull request #12
Opened 2020-11-08 20:05 UTC by MariaSarbaj

2020-11-08 20:07 UTC, MariaSarbaj commented
Сделала 2 задания в одном

2020-11-09 01:14 UTC, AlexMasterov requested changes
При доработке и после не забудь обновить бандл: `npm run build`.

2020-11-09 01:14 UTC, AlexMasterov commented on webpack.config.js
> +module.exports = {
Node.js загружает этот файл конфига как модуль CommonJS, в котором [строгий режим](https://developer.mozilla.org/ru/docs/web/javascript/reference/strict_mode) (= `use strict`) **не включен по умолчанию**.

Желательно в начало модуля добавить директиву `'use strict';`.

> В модулях ES6 строгий режим включен по умолчанию и использовать директиву не требуется

2020-11-09 01:14 UTC, AlexMasterov commented on js/uploadPhoto.js
> +          photoPreview.style.maxHeight = `${PHOTO_SIZE}`;
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/98489757-6c96b700-2240-11eb-861d-0519c5113c7f.png)

</details>


Вёрстка 🤔

<details>
<summary>uploadPhoto.js</summary>

https://github.com/htmlacademy-javascript/174891-keksobooking-21/blob/ceb557115e7deb1d79d583fadb035391e27e0a6b/js/uploadPhoto.js#L4
https://github.com/htmlacademy-javascript/174891-keksobooking-21/blob/ceb557115e7deb1d79d583fadb035391e27e0a6b/js/uploadPhoto.js#L37-L38
</details>

`70` _чего_?

Нужно для свойств `.maxWidth` / `.maxHeight` использовать _правильные_ значения.

Д4

2020-11-09 01:14 UTC, AlexMasterov commented on js/utils.js
> +    errorText.innerText = errorMessage;
<details>
<summary>utils.js</summary>

https://github.com/htmlacademy-javascript/174891-keksobooking-21/blob/ceb557115e7deb1d79d583fadb035391e27e0a6b/js/utils.js#L13-L14
</details>

```js
messageBody.querySelector(`.error__message`).textContent = errorMessage;
```

2020-11-09 06:53 UTC, AlexMasterov commented
👍🏻

2020-11-09 06:53 UTC, merged