Drag&drop
htmlacademy-javascript/174891-keksobooking-21 pull request #9
Opened 2020-11-03 09:05 UTC by MariaSarbaj

2020-11-03 12:29 UTC, AlexMasterov requested changes

2020-11-03 12:29 UTC, AlexMasterov commented on js/form.js
> +  const setAddress = function (location) {
`function`

Д28

Нужно использовать стрелочную запись функции `()`

2020-11-03 12:29 UTC, AlexMasterov commented on js/mainPinMoveHandler.js
> +      const mapPinsArea = document.querySelector(`.map__pins`);
[`Д 21`](https://up.htmlacademy.ru/javascript/21/criteries#d21)
> Поиск элементов по селекторам делается минимальное количество раз, после этого ссылки на элементы сохраняются

Нужно найти и сохранить ссылку на элемент за пределами функций _один_ раз, сохранить в переменную, а далее её только _переиспользовать_ внутри.

>  Также значение mapPinsArea.`offsetWidth` можно задать константой

2020-11-03 12:29 UTC, AlexMasterov commented on js/mainPinMoveHandler.js
> +      // Перемещаем метку в найденных границах
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/97984148-67241180-1de7-11eb-9f1d-829792e4d57c.png)
![image](https://user-images.githubusercontent.com/700213/97984174-72773d00-1de7-11eb-84c8-4a13e145b336.png)
</details>

`1199` вместо `1200`

> Возможно, что не критично

2020-11-03 12:29 UTC, AlexMasterov commented on js/mainPinMoveHandler.js
> +      // Перемещаем метку в найденных границах
<details>
<summary>Y (вверх)</summary>

![image](https://user-images.githubusercontent.com/700213/97984607-0b0dbd00-1de8-11eb-9ec0-449f483991ab.png)
![image](https://user-images.githubusercontent.com/700213/97984669-1bbe3300-1de8-11eb-885f-69cf5b2089de.png)

</details>
<details>
<summary>Y (низ)</summary>

![image](https://user-images.githubusercontent.com/700213/97984357-bbc78c80-1de7-11eb-9bff-188a1d3018e4.png)
![image](https://user-images.githubusercontent.com/700213/97984389-c550f480-1de7-11eb-815a-3fc7db37bae8.png)

</details>

См. [`ТЗ 4.4`](https://up.htmlacademy.ru/javascript/21/project/keksobooking#keksobooking-4-4):
> **значение Y-координаты адреса** должно быть ограничено интервалом от `130` до `630`

`217` вместо `130`
`717` вместо `630`

Нужно исправить.

2020-11-03 12:29 UTC, AlexMasterov commented on js/mainPinMoveHandler.js
> +    const onMapPinMouseMove = (moveEvt) => {
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/97984779-4ad4a480-1de8-11eb-86f3-8114a53530ec.png)
![image](https://user-images.githubusercontent.com/700213/97984818-57f19380-1de8-11eb-9e7d-80cfd2e2f0a1.png)
![image](https://user-images.githubusercontent.com/700213/97984853-663faf80-1de8-11eb-99c6-8f549336cef8.png)

</details>

См. ТЗ [`1.1`](https://up.htmlacademy.ru/javascript/21/project/keksobooking#keksobooking-1-1), [`4.1`](https://up.htmlacademy.ru/javascript/21/project/keksobooking#keksobooking-4-1):
> Первое взаимодействие с меткой (`mousedown`) переводит страницу в активное состояние

> при переходе страницы в активное состояние **в поле адреса подставляются координаты острого конца метки**

Сейчас в поле адреса подставляются координаты острого конца метки только после события `mouseup`.

Нужно доработать.

2020-11-03 13:10 UTC, AlexMasterov requested changes

2020-11-03 13:10 UTC, AlexMasterov commented on js/map.js
Если активировать страницу нажатием на `Enter` по главной метке, то координаты в поле адреса не изменяются.

Нужно доработать.

См. также [похожие замечание](https://github.com/htmlacademy-javascript/174891-keksobooking-21/pull/9#discussion_r516626468).

2020-11-04 15:08 UTC, MariaSarbaj commented
Я пока ждала предыдущую проверку начала делать следующее задание. Так что в этом коммите есть и его код. Можно не проверять и оставить на следующее задание, как будет удобно

2020-11-04 17:22 UTC, AlexMasterov approved these changes

2020-11-04 17:22 UTC, AlexMasterov commented on js/map.js
> +    addressInput.value = `${pinMainInitialPosition.x}, ${pinMainInitialPosition.y}`;
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/98142840-610e5d80-1ed9-11eb-9697-752dc9d7c659.png)

</details>

После деактивации страницы нажатием на кнопку `reset` поля адреса становится пустым.

См. [`ТЗ 4.2`](https://up.htmlacademy.ru/javascript/21/project/keksobooking#keksobooking-4-2):
> **Поле адреса должно быть заполнено всегда**, в том числе сразу после открытия страницы (в неактивном состоянии)

Нужно это учесть при доработке.

2020-11-04 17:22 UTC, AlexMasterov commented on js/map.js
> +  const setInactivateState = () => {
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/98143196-d5e19780-1ed9-11eb-9413-ce579952a2bb.png)

</details>

Если изменить тип жилья, а потом деактивировать страницы нажатием на кнопку `reset`, то значение цены становится некорректным.

Б1

Нужно после сброса страницы вернуть/зафиксировать значение `.min`, `.placeholder` у поля `#price`.

> Желательно так же явно запустить/зафиксировать валидацию на кол. комнат/мест

2020-11-04 17:22 UTC, AlexMasterov commented on js/utils.js
> +    document.addEventListener(`keydown`, onErrorMessageEscapeKeydown);
<details>
<summary>utils.js</summary>

https://github.com/htmlacademy-javascript/174891-keksobooking-21/blob/ec035e02cba23726400a87ee1a7ae253feede0dd/js/utils.js#L38
</details>

Не работает в Microsoft Edge — окно с сообщением не закрывается по нажатию на `Esc`.

 [`Б 21`](https://up.htmlacademy.ru/javascript/21/criteries#b21)

> При проверке этого критерия, необходимо удостовериться в правильной работе и отсутствии сообщений об ошибках в выполняемых скриптах только в последних версиях браузеров: Chrome, Firefox, Safari, **Microsoft Edge** (и на движке EdgeHTML, и на движке Blink)

Нужно разобраться и исправить.

> Возможно, что проблема сложна для понимании, но точно проста в вариантах исправления. Если не получится самостоятельно разораться, то прошу смело написать мне в чате ТГ. Объясню 😃

2020-11-04 17:22 UTC, AlexMasterov commented on js/map.js
> +  const setInactivateState = () => {
После успешной отправки формы страница переходит в неактивное состояние, но её больше нельзя повторно активировать, а главную метку можно перемещать 🤔

Нужно доработать.

2020-11-04 17:24 UTC, AlexMasterov commented
> Можно не проверять и оставить на следующее задание, как будет удобно

Формально задание для этого PR выполнено.

Изменений много, поэтому по новым замечаниям прошу доработать при выполнении следующего задания.

2020-11-04 17:24 UTC, merged